
package Secure;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Roya
 */
public class HotelInfo extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private MySqlConnection sql;
    private JPanel resultsContainer;
    
    /**
     * Creates new form HotelInfo
     */
    public HotelInfo(MySqlConnection mysql) {
    	this.sql = mysql;
        initComponents();
        setVisible(false);
    }
    
   
    void showHotel(String dateIn, String dateOut, String hotelName, String locations, String roomType, String minimumStars, String capacity, String minimumPrice){
    	
    	ArrayList<String> rs = sql.getHotelInfoForGuest(dateIn, dateOut, hotelName, locations, roomType, minimumStars, capacity, minimumPrice);
    	
    		for(int i = 0; i < rs.size(); i = i + 6) {
   
    			resultsContainer.add(new JLabel(rs.get(i)));
    			resultsContainer.add(new JLabel(rs.get(i + 1)));
    			resultsContainer.add(new JLabel(rs.get(i + 2)));
    			resultsContainer.add(new JLabel(rs.get(i + 3)));
    			resultsContainer.add(new JLabel(rs.get(i + 4)));
    			resultsContainer.add(new JLabel(rs.get(i + 5)));
    			resultsContainer.add(new JButton("Reserve this room"));
    		}
    			
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
    	//this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	this.setSize(1000,800);
    	this.setLocationRelativeTo(null);
    	this.resultsContainer = new JPanel();
    	this.resultsContainer.setLayout(new GridLayout(0,7));
    	
    	JPanel titles = new JPanel();
    	titles.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 25)); 
    	resultsContainer.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    	titles.setLayout(new GridLayout(0,7));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Name</font></b></u></html>"));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Address</font></b></u></html>"));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Type</font></b></u></html>"));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Stars #</font></b></u></html>"));
    	//titles.add(new JLabel("<html><u><b><font size=\"+1\">Availability</font></b></u></html>"));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Capacity</font></b></u></html>"));
    	titles.add(new JLabel("<html><u><b><font size=\"+1\">Cost</font></b></u></html>"));
    	titles.add(new JLabel());
    	
    	//showHotel(); //current used just for display, later remove and showhotel will be called when query inputs from user are given
    	
    	this.add(titles, BorderLayout.NORTH);
    	this.add(new JScrollPane(resultsContainer), BorderLayout.CENTER);
    	
    }

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HotelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HotelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HotelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HotelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HotelInfo(new MySqlConnection()).setVisible(true);
//            }
//        });
//    }
}
